# Generated by Django 2.2 on 2019-07-18 17:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hamsafar', '0002_auto_20190718_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='RequestTravel',
        ),
    ]
