# Generated by Django 2.2 on 2019-07-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamsafar', '0003_auto_20190718_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttravel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
