# Generated by Django 2.2 on 2019-07-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamsafar', '0005_auto_20190719_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttravel',
            name='end_city',
            field=models.CharField(default='safari', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttravel',
            name='start_city',
            field=models.CharField(default='khorasan', max_length=100),
            preserve_default=False,
        ),
    ]
